name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on: 
  push:
    branches: [ master]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on:  ubuntu-latest
    steps:
    #yses GitHub's checkout action to checkout code from the master branch
    - uses: actions/checkout@v2
    
    #sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0
        
    # publishes Blazor project ot the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish PFICWebUI/PFICWebUI.csproj -c Release -o release --nologo
        
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
